CREATE DATABASE FARMACIA
GO
USE FARMACIA
GO
CREATE TABLE USUARIOS
(
Codigo INT IDENTITY(1,1) NOT NULL,
Usuario varchar(30) NOT NULL,
Clave varchar(16)NULL,
)
INSERT INTO USUARIOS VALUES ('DULCE','123456')
SELECT * FROM USUARIOS
GO
CREATE TABLE CLIENTES
(
Codigo INT IDENTITY (1,1) NOT NULL,
Nombre VARCHAR(50)NULL,
Apellidos VARCHAR(50)NULL,
Direccion VARCHAR(250)NULL,
Celular VARCHAR(11) NULL,
Sexo varchar(15)
)
SELECT * FROM CLIENTES
GO
CREATE TABLE MEDICAMENTOS
(
CODIGO VARCHAR(50) NOT NULL,
Descripcion VARCHAR(50)NULL,
PrecioUnidad decimal(10,2)NULL,
PrecioCompra decimal(10,2)NULL,
FechaVencimiento datetime NULL,
Stock int,
CodigoCategoria VARCHAR(30)
)
GO
SELECT * FROM MEDICAMENTOS
CREATE TABLE PEDIDOS
(
Codigo INT IDENTITY (1,1) NOT NULL,
NombreCliente VARCHAR(50)NOT NULL,
Apellidos VARCHAR(30)NULL,
Direccion VARCHAR(30)NULL,
Producto VARCHAR(50)NOT NULL,
Cantidad int NOT null,
Precio decimal(10,2) nOT null
)
SELECT * FROM PEDIDOS




